### ISSUE TITLE
Relocation support?

### ISSUE THREAD

**Issue by LeeGodSRC** [bergerhealer/Mountiplex#12]
Currently if you relocated mountiplex you will receive this error, was relocation support planned or there is a workaround for this?

```
[21:05:18 ERROR]: [REFLECTION] Failed to get static field value
java.lang.RuntimeException: Failed to generate class
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.ExtendedClassWriter.generateConstructor(ExtendedClassWriter.java:295) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.ExtendedClassWriter.generateInstance(ExtendedClassWriter.java:333) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.fast.GeneratedConstructor.create(GeneratedConstructor.java:147) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.fast.ReflectionConstructor.create(ReflectionConstructor.java:105) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.FastConstructor$FastConstructorInitProxy.init(FastConstructor.java:168) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.FastConstructor$FastConstructorInitProxy.newInstance(FastConstructor.java:187) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.FastConstructor.newInstance(FastConstructor.java:127) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.TemplateHandleBuilder.create(TemplateHandleBuilder.java:44) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.Template$Class.createHandle(Template.java:134) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.Template$DuplexHandleConverter.convertInput(Template.java:565) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.Template$DuplexHandleConverter.convertInput(Template.java:554) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.conversion.type.LazyConverter$InitConverter.convertInput(LazyConverter.java:100) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.conversion.Converter.convert(Converter.java:47) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.Template$StaticField$Converted.get(Template.java:1992) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.declarations.Template$StaticField$Converted.getSafe(Template.java:1982) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.generated.net.minecraft.world.level.block.BlockHandle.<clinit>(BlockHandle.java:16) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.nms.modern.ModernNativeProvider.getPossibleDefinition(ModernNativeProvider.kt:145) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.nms.Native.getPossibleDefinition(Native.kt:59) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.data.MaterialDataHandler.decodeToPossibleIds(MaterialDataHandler.kt:58) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.obfuscator.impl.RaytraceAntiXrayObfuscator.<init>(RaytraceAntiXrayObfuscator.kt:27) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.obfuscator.provider.RaytraceObfuscatorProvider.create(RaytraceObfuscatorProvider.kt:29) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.AntiXrayControllerFactory.create(AntiXrayControllerFactory.kt:38) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.listener.WorldLoadListener.initWorld(WorldLoadListener.kt:136) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.listener.WorldLoadListener.initialize(WorldLoadListener.kt:66) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.listener.WorldLoadListener.onPostInitialize$lambda$0(WorldLoadListener.kt:42) ~[runServer-plugin.jar:?]
	at runServer-plugin.jar/dev.imanity.antixray.core.infrastructure.InitialTickProcessor.process(InitialTickProcessor.kt:27) ~[runServer-plugin.jar:?]
	at fairy-lib-plugin-0.7.5b1-SNAPSHOT-all.jar/io.fairyproject.bukkit.scheduler.folia.FoliaAbstractScheduler.lambda$schedule$2(FoliaAbstractScheduler.java:69) ~[fairy-lib-plugin-0.7.5b1-SNAPSHOT-all.jar:?]
	at fairy-lib-plugin-0.7.5b1-SNAPSHOT-all.jar/io.fairyproject.bukkit.scheduler.folia.FoliaAbstractScheduler.lambda$doSchedule$0(FoliaAbstractScheduler.java:47) ~[fairy-lib-plugin-0.7.5b1-SNAPSHOT-all.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-4-36e5e83]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-4-36e5e83]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-4-36e5e83]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-4-36e5e83]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/bergerkiller/mountiplex/reflection/util/fast/InvalidArgumentCountException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
	at java.base/java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
	at java.base/java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
	at runServer-plugin.jar/dev.imanity.antixray.libs.mountiplex.reflection.util.ExtendedClassWriter.generateConstructor(ExtendedClassWriter.java:293) ~[runServer-plugin.jar:?]
	... 34 more
```

**Comment by bergerkiller** [comment]
Ive never tested that, its possible in some places its hardcoding certain class names when it shouldn't. Not planned, but if you make a PR to adjust this I would accept it.

In this case, this is because of lines like this:
- https://github.com/bergerhealer/Mountiplex/blob/master/src/main/java/com/bergerkiller/mountiplex/reflection/util/fast/GeneratedConstructor.java#L75
- https://github.com/bergerhealer/Mountiplex/blob/master/src/main/java/com/bergerkiller/mountiplex/reflection/util/fast/GeneratedConstructor.java#L110

Which would have to be replaced with:

```
MPLType.getInternalName(GeneratedConstructor.class)
MPLType.getInternalName(InvalidArgumentCountException.class)
```

They are the way they are because I often use(d) the ASM dump tool to get the asm code of an existing method, which would write it out like the above.

There's definitely more places where it doesn't work when the classes are remapped by the shade plugin.
